runtime: python
env: flex
entrypoint: bash -c 'python3 manage.py collectstatic --noinput && python3 manage.py migrate --noinput && gunicorn -b :$PORT bellsCRM.wsgi'

handlers:
- url: /static
  static_dir: static/
- url: /.*
  script: auto
runtime_config:
  python_version: 3
