# Generated by Django 4.2.8 on 2024-08-28 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0012_alter_employee_options_alter_employee_created_by_and_more'),
        ('employee', '0002_alter_clientassignment_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientassignment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_assignments', to='userauth.employee'),
        ),
    ]
