# Generated by Django 4.2.16 on 2025-02-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_clientassignment_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idsandchecksdocuments',
            options={'permissions': [('import_all_documents', 'Can import all documents'), ('import_team_documents', 'Can import documents in their team'), ('import_own_documents', 'Can import documents of their own'), ('import_document_none', 'Restricted: No import permission'), ('read_all_documents', 'Can read all documents'), ('read_team_documents', 'Can read documents in their team'), ('read_own_documents', 'Can read documents of their own'), ('read_document_none', 'Restricted: No read permission'), ('delete_all_documents', 'Can delete all documents'), ('delete_team_documents', 'Can delete documents in their team'), ('delete_own_documents', 'Can delete documents of their own'), ('delete_document_none', 'Restricted: No delete permission')], 'verbose_name': 'IDs and Checks Document', 'verbose_name_plural': 'IDs and Checks Documents'},
        ),
        migrations.AlterField(
            model_name='clientassignment',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientassignment',
            name='updated_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientassignmentdetail',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientassignmentdetail',
            name='updated_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='idsandchecksdocuments',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='idsandchecksdocuments',
            name='updated_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='otherdocuments',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='otherdocuments',
            name='updated_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='qualificationdocuments',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='qualificationdocuments',
            name='updated_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
