# Generated by Django 4.2.8 on 2023-12-21 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=150)),
                ('address', models.TextField(blank=True, null=True)),
                ('contact', models.CharField(blank=True, max_length=20, null=True)),
                ('company_code', models.CharField(blank=True, max_length=50, null=True)),
                ('client_code', models.CharField(blank=True, max_length=50, null=True)),
                ('incident_report_code', models.CharField(blank=True, max_length=50, null=True)),
                ('employee_code', models.CharField(blank=True, max_length=50, null=True)),
                ('unique_url', models.URLField(blank=True, max_length=250, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='CompanyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('company_code', models.CharField(blank=True, max_length=50, null=True)),
                ('client_code', models.CharField(blank=True, max_length=50, null=True)),
                ('incident_report_code', models.CharField(blank=True, max_length=50, null=True)),
                ('employee_code', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_detail', to='bellscrm_admin.company')),
            ],
            options={
                'verbose_name': 'CompanyDetail',
                'verbose_name_plural': 'CompanyDetails',
            },
        ),
    ]
