# Generated by Django 4.2.8 on 2023-12-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bellscrm_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=250, null=True),
        ),
    ]
