# Generated by Django 4.2.8 on 2023-12-22 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bellscrm_admin', '0002_company_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='email',
            new_name='email_for_alerts',
        ),
    ]
