# Generated by Django 4.2.8 on 2023-12-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bellscrm_admin', '0003_rename_email_company_email_for_alerts'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='mandatory_incident_report_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
