# Generated by Django 4.2.8 on 2024-01-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bellscrm_admin', '0004_company_mandatory_incident_report_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='unique_url',
            new_name='login_url',
        ),
        migrations.AddField(
            model_name='company',
            name='register_url',
            field=models.URLField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
