# Generated by Django 4.2.8 on 2024-01-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bellscrm_admin', '0005_rename_unique_url_company_login_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companydetail',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
