# Generated by Django 4.2.8 on 2023-12-21 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bellscrm_admin', '0001_initial'),
        ('userauth', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('sno', models.IntegerField(default=1)),
                ('report_code', models.CharField(max_length=20)),
                ('incident_location', models.CharField(blank=True, max_length=150, null=True)),
                ('incident_date_time', models.DateTimeField(blank=True, null=True)),
                ('is_injured', models.BooleanField(default=False)),
                ('injured_person', models.TextField(blank=True, null=True)),
                ('action_taken', models.TextField(blank=True, null=True)),
                ('any_witness', models.BooleanField(default=False)),
                ('witness_name', models.CharField(blank=True, max_length=100, null=True)),
                ('witness_phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('witness_email', models.EmailField(blank=True, max_length=250, null=True)),
                ('story_of_incident', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('InProgress', 'InProgress'), ('Closed', 'Closed')], default='New', max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='userauth.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='bellscrm_admin.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='userauth.employee')),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
                'unique_together': {('company', 'sno')},
            },
        ),
        migrations.CreateModel(
            name='MandatoryIncident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('sno', models.IntegerField(default=1)),
                ('report_code', models.CharField(max_length=20)),
                ('incident_location', models.CharField(blank=True, max_length=150, null=True)),
                ('incident_date_time', models.DateTimeField(blank=True, null=True)),
                ('is_injured', models.BooleanField(default=False)),
                ('injured_person', models.TextField(blank=True, null=True)),
                ('action_taken', models.TextField(blank=True, null=True)),
                ('any_witness', models.BooleanField(default=False)),
                ('witness_name', models.CharField(blank=True, max_length=100, null=True)),
                ('witness_phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('witness_email', models.EmailField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('InProgress', 'InProgress'), ('Closed', 'Closed')], default='New', max_length=100)),
                ('story_of_incident', models.TextField(blank=True, null=True)),
                ('is_mandatory_aware', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandatory_incidents', to='userauth.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandatory_incidents', to='bellscrm_admin.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandatory_incidents', to='userauth.employee')),
            ],
            options={
                'verbose_name': 'MandatoryIncident',
                'verbose_name_plural': 'MandatoryIncidents',
                'unique_together': {('company', 'sno')},
            },
        ),
        migrations.CreateModel(
            name='MandatoryIncidentAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('file', models.FileField(upload_to='mandatory_incident_attachments/')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mandatory_incident_attachments', to='company_admin.mandatoryincident')),
            ],
            options={
                'verbose_name': 'MandatoryIncidentAttachment',
                'verbose_name_plural': 'MandatoryIncidentAttachments',
            },
        ),
        migrations.CreateModel(
            name='IncidentAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('file', models.FileField(upload_to='incident_attachments/')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incident_attachments', to='company_admin.incident')),
            ],
            options={
                'verbose_name': 'IncidentAttachment',
                'verbose_name_plural': 'IncidentAttachments',
            },
        ),
        migrations.CreateModel(
            name='DailyShiftCaseNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('sno', models.IntegerField(default=1)),
                ('start_date_time', models.DateTimeField(blank=True, null=True)),
                ('end_date_time', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_shift_case_notes', to='userauth.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_shift_case_notes', to='bellscrm_admin.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_shift_case_notes', to='userauth.employee')),
            ],
            options={
                'verbose_name': 'DailyShiftCaseNote',
                'verbose_name_plural': 'DailyShiftCaseNotes',
                'unique_together': {('company', 'sno')},
            },
        ),
    ]
