# Generated by Django 4.2.8 on 2024-01-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandatoryincidentattachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='mandatory_incident_attachments/'),
        ),
    ]
