# Generated by Django 4.2.8 on 2024-01-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_admin', '0002_alter_mandatoryincidentattachment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='action_taken',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_location',
            field=models.CharField(default='Test', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incident',
            name='story_of_incident',
            field=models.TextField(default='Test'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incidentattachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='incident_attachments/'),
        ),
        migrations.AlterField(
            model_name='mandatoryincident',
            name='action_taken',
            field=models.TextField(default='Test'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mandatoryincident',
            name='incident_location',
            field=models.CharField(default='Test', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mandatoryincident',
            name='story_of_incident',
            field=models.TextField(default='Test'),
            preserve_default=False,
        ),
    ]
