# Generated by Django 4.2.8 on 2024-01-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_admin', '0003_alter_incident_action_taken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='action_taken',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mandatoryincident',
            name='action_taken',
            field=models.TextField(blank=True),
        ),
    ]
