# Generated by Django 4.2.8 on 2024-01-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_admin', '0004_alter_incident_action_taken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentattachment',
            name='file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='incident_attachments/'),
        ),
        migrations.AlterField(
            model_name='mandatoryincidentattachment',
            name='file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='mandatory_incident_attachments/'),
        ),
    ]
