# Generated by Django 4.2.8 on 2024-04-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bellscrm_admin', '0007_alter_company_company_code'),
        ('company_admin', '0005_alter_incidentattachment_file_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='incident',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='incident',
            name='is_mandatory_aware',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incident',
            name='report_type',
            field=models.CharField(choices=[('Incident', 'Incident'), ('Mandatory Incident', 'Mandatory Incident')], default='Incident', max_length=100),
        ),
        migrations.AlterField(
            model_name='dailyshiftcasenote',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='incidentattachment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mandatoryincident',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mandatoryincidentattachment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='incident',
            unique_together={('company', 'sno', 'report_type')},
        ),
    ]
