# Generated by Django 4.2.8 on 2024-05-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_admin', '0007_riskassessment_risktype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='injured_person',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
