# Generated by Django 4.2.8 on 2024-06-13 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rostering', '0001_initial'),
        ('company_admin', '0009_incident_action_taken_for_individual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyshiftcasenote',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_shift_case_notes', to='rostering.shifts'),
        ),
        migrations.AlterField(
            model_name='dailyshiftcasenote',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
