# Generated by Django 5.0.1 on 2024-07-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_admin', '0011_incident_incident_severity_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandatoryincident',
            name='mandatory_incident_severity_level',
            field=models.CharField(choices=[('Harmful to self', 'Harmful to self '), ('Harmful to property ', 'Harmful to property '), ('Harmful to others', 'Harmful to others')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mandatoryincident',
            name='mandatory_specific_severity_level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
