# Generated by Django 5.0.1 on 2024-07-03 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_admin', '0012_mandatoryincident_mandatory_incident_severity_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mandatoryincident',
            name='mandatory_incident_severity_level',
        ),
        migrations.RemoveField(
            model_name='mandatoryincident',
            name='mandatory_specific_severity_level',
        ),
    ]
