# Generated by Django 5.0.1 on 2024-07-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_admin', '0013_remove_mandatoryincident_mandatory_incident_severity_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='incident_severity_level',
            field=models.CharField(choices=[('Harmful to self', 'Harmful to self'), ('Harmful to property ', 'Harmful to property'), ('Harmful to others', 'Harmful to others')], max_length=100),
        ),
    ]
