# Generated by Django 5.0.1 on 2024-08-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_admin', '0014_alter_incident_incident_severity_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='incident_severity_level',
            field=models.CharField(choices=[('Not applicable', 'Not applicable'), ('Harmful to self', 'Harmful to self'), ('Harmful to property', 'Harmful to property'), ('Harmful to others', 'Harmful to others')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='incident',
            name='specific_severity_level',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
