# Generated by Django 5.0.1 on 2024-08-22 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_admin', '0015_alter_incident_incident_severity_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='action_taken_for_individual',
            new_name='inbetween_incident_details',
        ),
        migrations.RenameField(
            model_name='incident',
            old_name='story_of_incident',
            new_name='pre_incident_details',
        ),
    ]
