# Generated by Django 5.0.1 on 2024-08-27 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_admin', '0016_rename_action_taken_for_individual_incident_inbetween_incident_details_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='riskassessment',
            managers=[
            ],
        ),
    ]
