# Generated by Django 4.2.8 on 2024-08-28 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rostering', '0004_alter_shifts_shift_type'),
        ('company_admin', '0017_alter_riskassessment_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyshiftcasenote',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_shift_case_notes', to='rostering.shifts'),
        ),
    ]
