# Generated by Django 5.0.1 on 2024-09-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_admin', '0018_alter_dailyshiftcasenote_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='cause_of_incident',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='prevention_of_incident',
            field=models.TextField(blank=True, null=True),
        ),
    ]
