# Generated by Django 5.0.1 on 2024-10-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_admin', '0020_incident_incident_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='incident_category',
            field=models.CharField(blank=True, choices=[('Near miss', 'Near miss'), ('Transportation incident', 'Transportation incident'), ('Emergency incident', 'Emergency incident'), ('Client incident', 'Client incident'), ('Property damage', 'Property damage'), ('Staff incident', 'Staff incident'), ('Medication incident', 'Medication incident'), ('WHS (Workplace Health and Safety)', 'WHS (Workplace Health and Safety)'), ('Behavioral incident', 'Behavioral incident')], max_length=255, null=True),
        ),
    ]
