# Generated by Django 5.0.1 on 2024-11-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_admin', '0021_alter_incident_incident_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='incident_classification',
            field=models.CharField(blank=True, choices=[('Moderate', 'Moderate'), ('Major', 'Major'), ('Minor', 'Minor'), ('Insignificant', 'Insignificant'), ('Catastrophic', 'Catastrophic')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_category',
            field=models.CharField(blank=True, choices=[('Sexual or Physical assault', 'Sexual or Physical assault'), ('Injury', 'Injury'), ('Medication incident', 'Medication incident'), ('Client illness', 'Client illness'), ('Death', 'Death'), ('Abuse or neglect', 'Abuse or neglect'), ('Work health and safety', 'Work health and safety'), ('Waste incident', 'Waste incident'), ('Unauthorized use of restrictive practice', 'Unauthorized use of restrictive practice'), ('Other (include text field - report owner to define the field)', 'Other (include text field - report owner to define the field)'), ('Near miss', 'Near miss'), ('Client behaviour of concern', 'Client behaviour of concern')], max_length=255, null=True),
        ),
    ]
