# Generated by Django 5.0.1 on 2024-11-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_admin', '0022_incident_incident_classification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='define_other_category',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_category',
            field=models.CharField(blank=True, choices=[('Work health and safety', 'Work health and safety'), ('Waste incident', 'Waste incident'), ('Client illness', 'Client illness'), ('Other', 'Other'), ('Abuse or neglect', 'Abuse or neglect'), ('Death', 'Death'), ('Unauthorized use of restrictive practice', 'Unauthorized use of restrictive practice'), ('Injury', 'Injury'), ('Client behaviour of concern', 'Client behaviour of concern'), ('Sexual or Physical assault', 'Sexual or Physical assault'), ('Near miss', 'Near miss'), ('Medication incident', 'Medication incident')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_classification',
            field=models.CharField(blank=True, choices=[('Moderate', 'Moderate'), ('Minor', 'Minor'), ('Insignificant', 'Insignificant'), ('Catastrophic', 'Catastrophic'), ('Major', 'Major')], max_length=255, null=True),
        ),
    ]
