# Generated by Django 5.0.1 on 2024-11-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_admin', '0023_incident_define_other_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='incident_category',
            field=models.CharField(blank=True, choices=[('Near miss', 'Near miss'), ('Client illness', 'Client illness'), ('Sexual or Physical assault', 'Sexual or Physical assault'), ('Unauthorized use of restrictive practice', 'Unauthorized use of restrictive practice'), ('Injury', 'Injury'), ('Abuse or neglect', 'Abuse or neglect'), ('Medication incident', 'Medication incident'), ('Death', 'Death'), ('Waste incident', 'Waste incident'), ('Other', 'Other'), ('Work health and safety', 'Work health and safety'), ('Client behaviour of concern', 'Client behaviour of concern')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_classification',
            field=models.CharField(blank=True, choices=[('Major', 'Major'), ('Catastrophic', 'Catastrophic'), ('Minor', 'Minor'), ('Moderate', 'Moderate'), ('Insignificant', 'Insignificant')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='pre_incident_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
