# Generated by Django 5.0.1 on 2024-11-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_admin', '0024_alter_incident_incident_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='incident_category',
            field=models.CharField(blank=True, choices=[('Unauthorized use of restrictive practice', 'Unauthorized use of restrictive practice'), ('Sexual or Physical assault', 'Sexual or Physical assault'), ('Near miss', 'Near miss'), ('Other', 'Other'), ('Client illness', 'Client illness'), ('Death', 'Death'), ('Abuse or neglect', 'Abuse or neglect'), ('Waste incident', 'Waste incident'), ('Work health and safety', 'Work health and safety'), ('Client behaviour of concern', 'Client behaviour of concern'), ('Medication incident', 'Medication incident'), ('Injury', 'Injury')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_classification',
            field=models.CharField(blank=True, choices=[('Insignificant', 'Insignificant'), ('Minor', 'Minor'), ('Major', 'Major'), ('Moderate', 'Moderate'), ('Catastrophic', 'Catastrophic')], max_length=255, null=True),
        ),
    ]
