# Generated by Django 5.0.1 on 2024-11-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_admin', '0025_alter_incident_incident_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='incident_category',
            field=models.CharField(blank=True, choices=[('Sexual or Physical assault', 'Sexual or Physical assault'), ('Near miss', 'Near miss'), ('Client illness', 'Client illness'), ('Work health and safety', 'Work health and safety'), ('Waste incident', 'Waste incident'), ('Medication incident', 'Medication incident'), ('Client behaviour of concern', 'Client behaviour of concern'), ('Other', 'Other'), ('Injury', 'Injury'), ('Unauthorized use of restrictive practice', 'Unauthorized use of restrictive practice'), ('Abuse or neglect', 'Abuse or neglect'), ('Death', 'Death')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_classification',
            field=models.CharField(blank=True, choices=[('Minor', 'Minor'), ('Moderate', 'Moderate'), ('Insignificant', 'Insignificant'), ('Catastrophic', 'Catastrophic'), ('Major', 'Major')], max_length=255, null=True),
        ),
    ]
