# Generated by Django 5.0.1 on 2024-11-22 07:57

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bellscrm_admin', '0007_alter_company_company_code'),
        ('company_admin', '0026_alter_incident_incident_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='incident_category',
            field=models.CharField(blank=True, choices=[('Injury', 'Injury'), ('Waste incident', 'Waste incident'), ('Other', 'Other'), ('Near miss', 'Near miss'), ('Client behaviour of concern', 'Client behaviour of concern'), ('Client illness', 'Client illness'), ('Sexual or Physical assault', 'Sexual or Physical assault'), ('Abuse or neglect', 'Abuse or neglect'), ('Work health and safety', 'Work health and safety'), ('Unauthorized use of restrictive practice', 'Unauthorized use of restrictive practice'), ('Death', 'Death'), ('Medication incident', 'Medication incident')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_classification',
            field=models.CharField(blank=True, choices=[('Catastrophic', 'Catastrophic'), ('Moderate', 'Moderate'), ('Minor', 'Minor'), ('Insignificant', 'Insignificant'), ('Major', 'Major')], max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='CompanyTermsAndConditionsPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('privacy_policy', 'privacy_policy'), ('terms_and_conditions', 'terms_and_conditions')], max_length=255)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='terms_and_conditions_policy', to='bellscrm_admin.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeePolicyAcknowledgment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgments', to='company_admin.companytermsandconditionspolicy')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
