# Generated by Django 5.0.1 on 2024-11-25 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bellscrm_admin', '0007_alter_company_company_code'),
        ('company_admin', '0027_alter_incident_incident_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companytermsandconditionspolicy',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms_and_conditions_policy', to='bellscrm_admin.company'),
        ),
        migrations.AlterField(
            model_name='companytermsandconditionspolicy',
            name='type',
            field=models.CharField(choices=[('terms_and_conditions', 'terms_and_conditions'), ('privacy_policy', 'privacy_policy')], max_length=255),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_category',
            field=models.CharField(blank=True, choices=[('Unauthorized use of restrictive practice', 'Unauthorized use of restrictive practice'), ('Client behaviour of concern', 'Client behaviour of concern'), ('Death', 'Death'), ('Medication incident', 'Medication incident'), ('Client illness', 'Client illness'), ('Near miss', 'Near miss'), ('Sexual or Physical assault', 'Sexual or Physical assault'), ('Abuse or neglect', 'Abuse or neglect'), ('Work health and safety', 'Work health and safety'), ('Waste incident', 'Waste incident'), ('Injury', 'Injury'), ('Other', 'Other')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_classification',
            field=models.CharField(blank=True, choices=[('Insignificant', 'Insignificant'), ('Catastrophic', 'Catastrophic'), ('Minor', 'Minor'), ('Major', 'Major'), ('Moderate', 'Moderate')], max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='companytermsandconditionspolicy',
            unique_together={('company', 'type')},
        ),
    ]
