# Generated by Django 4.2.8 on 2024-11-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_admin', '0029_alter_companytermsandconditionspolicy_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='incident_category',
            field=models.CharField(blank=True, choices=[('Death', 'Death'), ('Other', 'Other'), ('Work health and safety', 'Work health and safety'), ('Waste incident', 'Waste incident'), ('Client behaviour of concern', 'Client behaviour of concern'), ('Medication incident', 'Medication incident'), ('Abuse or neglect', 'Abuse or neglect'), ('Unauthorized use of restrictive practice', 'Unauthorized use of restrictive practice'), ('Sexual or Physical assault', 'Sexual or Physical assault'), ('Near miss', 'Near miss'), ('Injury', 'Injury'), ('Client illness', 'Client illness')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_classification',
            field=models.CharField(blank=True, choices=[('Insignificant', 'Insignificant'), ('Major', 'Major'), ('Catastrophic', 'Catastrophic'), ('Moderate', 'Moderate'), ('Minor', 'Minor')], max_length=255, null=True),
        ),
    ]
