# Generated by Django 4.2.8 on 2024-11-27 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0013_employee_employment_type'),
        ('company_admin', '0030_alter_incident_incident_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepolicyacknowledgment',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policy_acknowledgments', to='userauth.employee'),
        ),
        migrations.AlterField(
            model_name='companytermsandconditionspolicy',
            name='type',
            field=models.CharField(choices=[('terms_and_conditions', 'terms_and_conditions'), ('privacy_policy', 'privacy_policy')], max_length=255),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_category',
            field=models.CharField(blank=True, choices=[('Client behaviour of concern', 'Client behaviour of concern'), ('Unauthorized use of restrictive practice', 'Unauthorized use of restrictive practice'), ('Death', 'Death'), ('Sexual or Physical assault', 'Sexual or Physical assault'), ('Client illness', 'Client illness'), ('Abuse or neglect', 'Abuse or neglect'), ('Other', 'Other'), ('Injury', 'Injury'), ('Near miss', 'Near miss'), ('Waste incident', 'Waste incident'), ('Work health and safety', 'Work health and safety'), ('Medication incident', 'Medication incident')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_classification',
            field=models.CharField(blank=True, choices=[('Minor', 'Minor'), ('Moderate', 'Moderate'), ('Insignificant', 'Insignificant'), ('Catastrophic', 'Catastrophic'), ('Major', 'Major')], max_length=255, null=True),
        ),
    ]
