# Generated by Django 4.2.16 on 2024-12-04 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0013_employee_employment_type'),
        ('company_admin', '0031_employeepolicyacknowledgment_employee_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companytermsandconditionspolicy',
            options={'verbose_name': 'Incident Tag', 'verbose_name_plural': 'Incident Tags'},
        ),
        migrations.AlterModelOptions(
            name='employeepolicyacknowledgment',
            options={'verbose_name': 'Employee Policy Acknowledgment', 'verbose_name_plural': 'Employee Policy Acknowledgments'},
        ),
        migrations.AlterUniqueTogether(
            name='companytermsandconditionspolicy',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='incident',
            name='employees_involved',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='no', max_length=255),
        ),
        migrations.AlterField(
            model_name='companytermsandconditionspolicy',
            name='type',
            field=models.CharField(choices=[('terms_and_conditions', 'Terms and Conditions'), ('privacy_policy', 'Privacy Policy')], max_length=255),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_category',
            field=models.CharField(blank=True, choices=[('Injury', 'Injury'), ('Sexual or Physical assault', 'Sexual or Physical assault'), ('Death', 'Death'), ('Abuse or neglect', 'Abuse or neglect'), ('Unauthorized use of restrictive practice', 'Unauthorized use of restrictive practice'), ('Waste incident', 'Waste incident'), ('Medication incident', 'Medication incident'), ('Client behaviour of concern', 'Client behaviour of concern'), ('Client illness', 'Client illness'), ('Work health and safety', 'Work health and safety'), ('Near miss', 'Near miss'), ('Other', 'Other')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_classification',
            field=models.CharField(blank=True, choices=[('Catastrophic', 'Catastrophic'), ('Major', 'Major'), ('Moderate', 'Moderate'), ('Minor', 'Minor'), ('Insignificant', 'Insignificant')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_severity_level',
            field=models.CharField(choices=[('Not applicable', 'Not applicable'), ('Harmful to self', 'Harmful to self'), ('Harmful to property', 'Harmful to property'), ('Harmful to others', 'Harmful to others')], max_length=255),
        ),
        migrations.CreateModel(
            name='IncidentTaggedEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_incident', to='company_admin.incident')),
                ('tagged_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_employee', to='userauth.employee')),
            ],
            options={
                'verbose_name': 'Incident Tag',
                'verbose_name_plural': 'Incident Tags',
            },
        ),
    ]
