# Generated by Django 4.2.16 on 2024-12-05 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_admin', '0032_alter_companytermsandconditionspolicy_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='employees_involved',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=255),
        ),
    ]
