# Generated by Django 4.2.16 on 2024-12-05 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bellscrm_admin', '0007_alter_company_company_code'),
        ('company_admin', '0033_alter_incident_employees_involved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companytermsandconditionspolicy',
            options={'verbose_name': 'Company Terms and Conditions Policy', 'verbose_name_plural': 'Company Terms and Conditions Policies'},
        ),
        migrations.AlterUniqueTogether(
            name='companytermsandconditionspolicy',
            unique_together={('company', 'type')},
        ),
    ]
