# Generated by Django 4.2.16 on 2024-12-05 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0013_employee_employment_type'),
        ('company_admin', '0034_alter_companytermsandconditionspolicy_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidenttaggedemployee',
            name='tagged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tagged_by_user', to='userauth.employee'),
        ),
        migrations.AddField(
            model_name='incidenttaggedemployee',
            name='untagged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='untagged_by_user', to='userauth.employee'),
        ),
    ]
