# Generated by Django 4.2.16 on 2024-12-05 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_admin', '0036_incidenttaggedemployee_is_removed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidenttaggedemployee',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='incidenttaggedemployee',
            name='tagged_to_client',
        ),
        migrations.RemoveField(
            model_name='incidenttaggedemployee',
            name='tagged_to_employee',
        ),
    ]
