# Generated by Django 4.2.16 on 2024-12-05 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0013_employee_employment_type'),
        ('company_admin', '0037_remove_incidenttaggedemployee_is_removed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidenttaggedemployee',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incidenttaggedemployee',
            name='tagged_to_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tagged_to_client', to='userauth.client'),
        ),
        migrations.AddField(
            model_name='incidenttaggedemployee',
            name='tagged_to_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tagged_to_employee', to='userauth.employee'),
        ),
    ]
