# Generated by Django 5.0.1 on 2024-12-20 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_admin', '0038_incidenttaggedemployee_is_removed_and_more'),
        ('userauth', '0013_employee_employment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidenttaggedemployee',
            name='tagged_to_client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tagged_to_client', to='userauth.client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incidenttaggedemployee',
            name='tagged_to_employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tagged_to_employee', to='userauth.employee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='riskassessmentdetail',
            name='risk_to_other_category',
            field=models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='riskassessmentdetail',
            name='risk_to_self_category',
            field=models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='riskassessmentdetail',
            name='risk_to_staff_category',
            field=models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=100, null=True),
        ),
    ]
