# Generated by Django 4.2.8 on 2025-01-09 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0014_alter_department_employees'),
        ('company_admin', '0039_alter_incidenttaggedemployee_tagged_to_client_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientEmployeeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_employee_assignments', to='userauth.client')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_employee_assignments', to='userauth.employee')),
            ],
            options={
                'verbose_name': 'Client Employee Assignment',
                'verbose_name_plural': 'Client Employee Assignments',
            },
        ),
    ]
