# Generated by Django 4.2.16 on 2025-03-18 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_admin', '0039_alter_incidenttaggedemployee_tagged_to_client_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyshiftcasenote',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='dailyshiftcasenote',
            name='sno',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
