# Generated by Django 4.2.8 on 2025-01-10 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0014_alter_department_employees'),
        ('company_admin', '0040_clientemployeeassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentClientAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_client_assignments', to='userauth.client')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_client_assignments', to='userauth.department')),
            ],
            options={
                'verbose_name': 'Department Client Assignment',
                'verbose_name_plural': 'Department Client Assignments',
            },
        ),
    ]
