# Generated by Django 4.2.16 on 2025-03-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_admin', '0040_alter_dailyshiftcasenote_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='report_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='sno',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
