# Generated by Django 4.2.16 on 2025-03-19 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_admin', '0041_alter_incident_report_code_alter_incident_sno'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='incident',
            unique_together=set(),
        ),
    ]
