# Generated by Django 4.2.16 on 2025-03-03 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_admin', '0042_alter_clientemployeeassignment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='riskassessment',
            options={'permissions': [('create_all_risk_assessments', 'Can create all risk assessments'), ('create_risk_assessments_team_own', 'Can create risk assessments for their own team'), ('create_risk_assessments_of_their_own', 'Can create their own risk assessments'), ('create_none', 'No permission to create risk assessments'), ('read_all_risk_assessments', 'Can read all risk assessments'), ('read_risk_assessments_team_own', 'Can read risk assessments for their own team'), ('read_risk_assessments_of_their_own', 'Can read their own risk assessments'), ('read_none', 'No permission to read risk assessments'), ('update_all_risk_assessments', 'Can update all risk assessments'), ('update_team_risk_assessments', 'Can update risk assessments for their own team'), ('update_own_risk_assessments', 'Can update their own risk assessments'), ('risk_assessment_update_none', 'No permission to update risk assessments'), ('delete_all_risk_assessments', 'Can delete all risk assessments'), ('delete_risk_assessments_team_own', 'Can delete risk assessments for their own team'), ('authorize_risk_assessment_all', 'Can authorize risk assessments for all teams'), ('authorize_risk_assessment_own_team', 'Can authorize risk assessments for their own team'), ('review_risk_assessment_all', 'Can review risk assessments for all teams'), ('review_risk_assessment_own_team', 'Can review risk assessments for their own team')], 'verbose_name': 'Risk Assessment', 'verbose_name_plural': 'Risk Assessments'},
        ),
    ]
