# Generated by Django 4.2.16 on 2025-04-19 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_admin', '0042_alter_incident_unique_together'),
        ('company_admin', '0043_alter_riskassessment_options'),
    ]

    operations = [
    ]
