# Generated by Django 4.2.16 on 2025-04-29 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0017_alter_department_options'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('bellscrm_admin', '0008_remove_company_mandatory_incident_report_code_and_more'),
        ('company_admin', '0044_merge_20250419_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentStageMapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_overdue', models.BooleanField(default=False)),
                ('stage_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to='userauth.employee')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_stage_mappings', to='company_admin.incident')),
            ],
            options={
                'verbose_name': 'Incident Stage Mapper',
                'verbose_name_plural': 'Incident Stage Mappers',
            },
        ),
        migrations.CreateModel(
            name='InvestigationHierarchy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('hierarchy_timeline_days', models.PositiveIntegerField()),
                ('levels', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('incident_investigation_hierarchy', 'Incident Investigation Hierarchy')], default='incident_investigation_hierarchy', max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigation_hierarchies', to='bellscrm_admin.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to='userauth.employee')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to='userauth.employee')),
            ],
            options={
                'verbose_name': 'Investigation Hierarchy',
                'verbose_name_plural': 'Investigation Hierarchies',
            },
        ),
        migrations.CreateModel(
            name='InvestigationStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('stage_name', models.CharField(max_length=255)),
                ('s_no', models.PositiveIntegerField(default=1)),
                ('version', models.PositiveIntegerField(default=1)),
                ('stage_timeline_days', models.PositiveIntegerField()),
                ('overdue_date', models.DateTimeField(blank=True, null=True)),
                ('is_overdue', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to='userauth.employee')),
                ('hierarchy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='company_admin.investigationhierarchy')),
                ('permissions', models.ManyToManyField(related_name='investigation_stages', to='auth.permission')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to='userauth.employee')),
            ],
            options={
                'verbose_name': 'Investigation Stage',
                'verbose_name_plural': 'Investigation Stages',
                'permissions': [('can_change_to_inprogress_not_closed', 'Can change incident status to InProgress but not Closed'), ('can_mark_inprogress_and_closed', 'Can change the incident report status to In Progress and can mark it as Closed'), ('can_view_incident_investigation_details', 'View the incident and investigation details')],
            },
        ),
        migrations.CreateModel(
            name='InvestigationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('question', models.TextField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to='userauth.employee')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigation_questions', to='company_admin.investigationstage')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to='userauth.employee')),
            ],
            options={
                'verbose_name': 'Investigation Question',
                'verbose_name_plural': 'Investigation Questions',
            },
        ),
        migrations.CreateModel(
            name='IncidentStageQuestionMapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('answer', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to='userauth.employee')),
                ('incident_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_admin.incidentstagemapper')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_admin.investigationquestion')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to='userauth.employee')),
            ],
            options={
                'verbose_name': 'Incident Stage Question Mapper',
                'verbose_name_plural': 'Incident Stage Question Mappers',
            },
        ),
        migrations.AddField(
            model_name='incidentstagemapper',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_mappings', to='company_admin.investigationstage'),
        ),
        migrations.AddField(
            model_name='incidentstagemapper',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to='userauth.employee'),
        ),
        migrations.CreateModel(
            name='StageOwnerSubstitute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('substitute_timeline_days', models.PositiveIntegerField()),
                ('subsitute_overdue_date', models.DateTimeField(blank=True, null=True)),
                ('is_subsitute_time_line_overdue', models.BooleanField(default=False)),
                ('is_substitute_active', models.BooleanField(blank=True, default=None, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to='userauth.employee')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_owner', to='userauth.employee')),
                ('removed_stage_subsitute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='removed_stage_substitute', to='userauth.employee')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_owners', to='company_admin.investigationstage')),
                ('substitute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stage_substitute', to='userauth.employee')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to='userauth.employee')),
            ],
            options={
                'verbose_name': 'Stage Owner Substitute',
                'verbose_name_plural': 'Stage Owner Substitutes',
                'unique_together': {('stage', 'owner', 'substitute')},
            },
        ),
    ]
