# Generated by Django 4.2.16 on 2025-04-29 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_admin', '0045_incidentstagemapper_investigationhierarchy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='investigation_hierarchy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='company_admin.investigationhierarchy'),
        ),
    ]
