# Generated by Django 4.2.16 on 2025-05-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_admin', '0046_incident_investigation_hierarchy'),
    ]

    operations = [
        migrations.AddField(
            model_name='stageownersubstitute',
            name='is_substitute_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
