# Generated by Django 4.2.16 on 2025-05-02 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bellscrm_admin', '0008_remove_company_mandatory_incident_report_code_and_more'),
        ('company_admin', '0047_stageownersubstitute_is_substitute_email_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigationhierarchy',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investigation_hierarchy', to='bellscrm_admin.company'),
        ),
    ]
