# Generated by Django 4.2.8 on 2025-05-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_admin', '0048_alter_investigationhierarchy_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='is_investigation_email_sent',
            field=models.BooleanField(default=True),
        ),
    ]
