# Generated by Django 4.2.8 on 2025-05-15 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_admin', '0049_incident_is_investigation_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyshiftcasenote',
            name='file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='progress_notes_attachments/'),
        ),
    ]
