# Generated by Django 4.2.8 on 2023-12-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
