# Generated by Django 4.2.8 on 2024-01-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_alter_person_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(error_messages={'unique': 'This email address is already associated with an account.'}, max_length=254, unique=True),
        ),
    ]
