# Generated by Django 4.2.8 on 2024-08-20 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0009_alter_person_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': [('edit_role', 'Can edit role'), ('add_role', 'Can add role'), ('add_is_active', 'Can approve employee'), ('edit_is_active', 'Can dis-approve employee'), ('disable_admin_choice', 'Can disable admin choice')], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
    ]
