# Generated by Django 5.0.1 on 2024-08-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0010_alter_employee_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientndisdetail',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientndisdetail',
            name='hours_requested',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientndisdetail',
            name='ndis_services',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='clientndisdetail',
            name='service_fund_type',
            field=models.CharField(choices=[('NDIS', 'NDIS'), ('Government Insurance scheme (e.g., TAX, SIRA, etc.)', 'Government Insurance scheme (e.g., TAX, SIRA, etc.)'), ('Self-funded', 'Self-funded'), ('Other', 'Other')], default='NDIS', max_length=100),
        ),
    ]
