# Generated by Django 5.0.1 on 2024-10-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0012_alter_employee_options_alter_employee_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employment_type',
            field=models.CharField(choices=[('Permanent staff', 'Permanent staff'), ('Permanent part-time', 'Permanent part-time'), ('Casual staff', 'Casual staff')], default='Permanent staff', max_length=255),
        ),
    ]
