# Generated by Django 4.2.8 on 2025-01-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0013_employee_employment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='employees',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('role__in', [1, 2]), _negated=True), related_name='assigned_departments', to='userauth.employee'),
        ),
    ]
