# Generated by Django 4.2.16 on 2025-02-28 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('userauth', '0014_alter_department_employees'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'permissions': [('create_all_clients', 'Can create all clients'), ('create_client_none', 'No permission to create clients'), ('update_all_clients', 'Can update all clients'), ('update_clients_team_owns', 'Can update clients owned by their own team'), ('update_clients_of_own', 'Can update their own clients'), ('client_update_none', 'No permission to update clients'), ('read_all_clients', 'Can read all clients'), ('read_team_clients', 'Can read clients owned by their own team')], 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'permissions': [('create_department_all', 'Can create all departments'), ('create_department_none', 'No permission to create department'), ('read_department_all', 'Can read all departments'), ('read_department_own', 'Can read department of there own'), ('read_department_none', 'No access to read department'), ('update_department_all', 'Can update all departments'), ('update_department_team_own', 'Can update department for their own team'), ('update_department_none', 'No access to update department'), ('delete_custom_department_all', 'Can delete all departments'), ('delete_department_own', 'Can delete department for their own team'), ('delete_department_none', 'No access to delete department'), ('update_assign_manager_to_department', 'Can assign manager to department'), ('update_clients_to_department', 'Can assign clients to department'), ('update_own_clients_to_department', 'Can assign own clients to department')], 'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': [('create_all_employees', 'Can create all employees'), ('create_employee_none', 'Restricted: No create permission'), ('update_all_employees', 'Can update all employees'), ('update_team_employees', 'Can update employees in their team'), ('update_own_employee', 'Can update self profile'), ('employee_update_none', 'Restricted: No update permission'), ('read_all_employees', 'Can read all employees'), ('read_team_employees', 'Can read employees in their team'), ('read_own_employee', 'Can read self profile'), ('update_employee_approval_all', 'Can update employee approval status'), ('update_employee_approval_none', 'Can not update employee approval status'), ('read_all_acknowledgements', 'Can read all acknowledgements'), ('read_team_acknowledgements', 'Can read acknowledgement their team owns')], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': [('create_templates', 'Can create templates'), ('create_templates_none', 'No permission to create templates'), ('update_templates', 'Can update templates for all users'), ('update_templates_none', 'No permission to update templates'), ('read_templates', 'Can read templates'), ('read_templates_none', 'No permission to read templates')], 'verbose_name': 'Person', 'verbose_name_plural': 'Persons'},
        ),
        migrations.AddField(
            model_name='employee',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='updated_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientemergencydetail',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientemergencydetail',
            name='updated_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientmedicaldetail',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientmedicaldetail',
            name='updated_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientndisdetail',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientndisdetail',
            name='updated_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='assigned_departments', to='userauth.employee'),
        ),
        migrations.AlterField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to='userauth.employee'),
        ),
        migrations.AlterField(
            model_name='department',
            name='updated_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.IntegerField(blank=True, choices=[(1, 'Admin'), (2, 'Manager'), (3, 'Employee')], default=3, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='updated_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='updated_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
