# Generated by Django 4.2.16 on 2025-03-02 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0015_alter_client_options_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'permissions': [('create_department_all', 'Can create all departments'), ('create_department_none', 'No permission to create department'), ('read_department_all', 'Can read all departments'), ('read_department_own', 'Can read department of there own'), ('read_department_none', 'No access to read department'), ('update_department_all', 'Can update all departments'), ('update_department_own', 'Can update department for their own own'), ('update_department_none', 'No access to update department'), ('delete_custom_department_all', 'Can delete all departments'), ('delete_department_own', 'Can delete department for their own team'), ('delete_department_none', 'No access to delete department'), ('update_assign_manager_to_department', 'Can assign manager to department'), ('update_clients_to_department', 'Can assign clients to department'), ('update_own_clients_to_department', 'Can assign own clients to department')], 'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': [('create_all_employees', 'Can create all employees'), ('create_employee_none', 'Restricted: No create permission'), ('update_all_employees', 'Can update all employees'), ('update_team_employees', 'Can update employees in their team'), ('update_own_employees', 'Can update self profile'), ('employee_update_none', 'Restricted: No update permission'), ('read_all_employees', 'Can read all employees'), ('read_team_employees', 'Can read employees in their team'), ('read_own_employees', 'Can read self profile'), ('update_employee_approval_all', 'Can update employee approval status'), ('update_employee_approval_none', 'Can not update employee approval status'), ('read_all_acknowledgements', 'Can read all acknowledgements'), ('read_team_acknowledgements', 'Can read acknowledgement their team owns')], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
    ]
