# Generated by Django 4.2.16 on 2025-04-19 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0016_alter_department_options_alter_employee_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'permissions': [('create_department_all', 'Can create all teams'), ('create_department_none', 'No permission to create team'), ('read_department_all', 'Can read all teams'), ('read_department_own', 'Can read team of there own'), ('read_department_none', 'No access to read team'), ('update_department_all', 'Can update all teams'), ('update_department_own', 'Can update team for their own own'), ('update_department_none', 'No access to update team'), ('delete_custom_department_all', 'Can delete all teams'), ('delete_department_own', 'Can delete team for their own team'), ('delete_department_none', 'No access to delete team'), ('update_assign_manager_to_department', 'Can assign manager to team'), ('update_clients_to_department', 'Can assign clients to team'), ('update_own_clients_to_department', 'Can assign own clients to team')], 'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
    ]
