# Generated by Django 5.0.1 on 2024-07-31 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rostering', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shifts',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Ongoing', 'Ongoing'), ('Assigned', 'Assigned'), ('Draft', 'Draft'), ('Progress note pending', 'Progress note pending')], default='Draft', max_length=100),
        ),
    ]
