# Generated by Django 5.0.1 on 2024-07-31 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rostering', '0002_alter_shifts_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shifts',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Ongoing', 'Ongoing'), ('Assigned', 'Assigned'), ('Draft', 'Draft'), ('Pending', 'Pending')], default='Draft', max_length=100),
        ),
    ]
