# Generated by Django 5.0.1 on 2024-08-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rostering', '0003_alter_shifts_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shifts',
            name='shift_type',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening'), ('Night', 'Night'), ('Open shift', 'Open shift')], max_length=100),
        ),
    ]
