# Generated by Django 4.2.16 on 2025-02-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rostering', '0004_alter_shifts_shift_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shifts',
            options={'permissions': [('create_shift_all', 'Can create all client shifts'), ('create_own_team_shift', 'Can create shifts for their own team'), ('create_shift_none', 'No access to create shifts'), ('update_shift_all', 'Can update all client shifts'), ('update_own_team_shift', 'Can update shifts for their own team'), ('update_roster_shift_none', 'No access to update roster shifts'), ('read_client_shift_all', 'Can read all client shifts'), ('read_own_team_shift', 'Can read shifts for their own team'), ('read_own_shift', 'Can read their own shifts'), ('read_no_shift_access', 'No access to read shifts'), ('view_dashboard_all_shifts', 'Can view all client shifts on the dashboard'), ('view_dashboard_own_team_shifts', 'Can view shifts for their own team on the dashboard'), ('view_dashboard_own_shifts', 'Can view their own shifts on the dashboard'), ('view_no_dashboard_access', 'No access to view shifts on the dashboard'), ('delete_shift_all', 'Can delete all client shifts'), ('delete_own_team_shift', 'Can delete shifts for their own team'), ('delete_no_shift_access', 'No access to delete shifts'), ('export_all_shift_reports', 'Can export all shift reports'), ('export_own_team_shift_reports', 'Can export shift reports for their own team'), ('export_shift_reports_none', 'No access to export shift report'), ('view_all_shift_reports', 'Can view all shift reports'), ('view_own_team_shift_reports', 'Can view shift reports for their own team'), ('update_employee_punch_in_out_own_shifts', 'Can update punch-in and punch-out for their own shifts'), ('update_employee_punch_in_out_no_access', 'No permission to update punch-in and punch-out'), ('view_own_shifts', 'Can view punch-in and punch-out for their own shifts'), ('view_no_access', 'No permission to view punch-in and punch-out')], 'verbose_name': 'Shift', 'verbose_name_plural': 'Shifts'},
        ),
        migrations.AlterField(
            model_name='shifts',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shifts',
            name='updated_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
